# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 036621c5fbafa045d8a79f75b846e9a4c42f68bbea9bc617b31870f116ca711e8545b830268ed95d75de90f8e490cac3b3a8c40969d735967e962574f45a5b16

test:
  secret_key_base: aedcc0dad5219b8841c996b38820b5b02f739614510a80cc21196294fe1eb5ac98397f7704907b260e48a1a2eabc6bb87afebedf9ddf62e8db619f7b01b82f28

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
